package tablas;
// Generated 12 dic 2022 12:03:06 by Hibernate Tools 6.0.2.Final

/**
 * ClientesId generated by hbm2java
 */
public class ClientesId implements java.io.Serializable {

	private String apellidos;
	private String direccion;
	private String email;
	private int id;
	private String nombre;
	private int telefono;
	private boolean vip;

	public ClientesId() {
	}

	public ClientesId(String apellidos, String direccion, String email, int id, String nombre, int telefono,
			boolean vip) {
		this.apellidos = apellidos;
		this.direccion = direccion;
		this.email = email;
		this.id = id;
		this.nombre = nombre;
		this.telefono = telefono;
		this.vip = vip;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getTelefono() {
		return this.telefono;
	}

	public void setTelefono(int telefono) {
		this.telefono = telefono;
	}

	public boolean isVip() {
		return this.vip;
	}

	public void setVip(boolean vip) {
		this.vip = vip;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClientesId))
			return false;
		ClientesId castOther = (ClientesId) other;

		return ((this.getApellidos() == castOther.getApellidos()) || (this.getApellidos() != null
				&& castOther.getApellidos() != null && this.getApellidos().equals(castOther.getApellidos())))
				&& ((this.getDireccion() == castOther.getDireccion()) || (this.getDireccion() != null
						&& castOther.getDireccion() != null && this.getDireccion().equals(castOther.getDireccion())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& (this.getId() == castOther.getId())
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& (this.getTelefono() == castOther.getTelefono()) && (this.isVip() == castOther.isVip());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getApellidos() == null ? 0 : this.getApellidos().hashCode());
		result = 37 * result + (getDireccion() == null ? 0 : this.getDireccion().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + this.getId();
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + this.getTelefono();
		result = 37 * result + (this.isVip() ? 1 : 0);
		return result;
	}

}
