package com.modelo;
// Generated 8 feb 2023 10:45:20 by Hibernate Tools 5.6.12.Final

/**
 * Cancion generated by hbm2java
 */
public class Cancion implements java.io.Serializable {

	private Integer idCancion;
	private Cantante cantante;
	private Disco disco;
	private String nombre;
	private String duracion;
	private String estilo;

	public Cancion() {
	}

	public Cancion(Cantante cantante, String nombre, String duracion) {
		this.cantante = cantante;
		this.nombre = nombre;
		this.duracion = duracion;
	}

	public Cancion(Cantante cantante, Disco disco, String nombre, String duracion, String estilo) {
		this.cantante = cantante;
		this.disco = disco;
		this.nombre = nombre;
		this.duracion = duracion;
		this.estilo = estilo;
	}
	
	/* Constructor sin disco*/
	/*
	public Cancion(int id_cancion, String nombre, String duracion, String estilo, int id_cantante) {
		super();
		this.id_cancion = id_cancion;
		this.nombre = nombre;
		this.duracion = duracion;
		this.estilo = estilo;
		this.id_cantante = id_cantante;
	}

	
	 Constructor sin estilo 
	public Cancion(int id_cancion, String nombre, String duracion, int id_cantante, int id_disco) {
		super();
		this.id_cancion = id_cancion;
		this.nombre = nombre;
		this.duracion = duracion;
		this.id_cantante = id_cantante;
		this.id_disco = id_disco;
	}
	
	 Constructor sin disco y sin estilo 
	public Cancion(int id_cancion, String nombre, String duracion, int id_cantante) {
		super();
		this.id_cancion = id_cancion;
		this.nombre = nombre;
		this.duracion = duracion;
		this.id_cantante = id_cantante;
	}*/
	
	public Integer getIdCancion() {
		return this.idCancion;
	}

	public void setIdCancion(Integer idCancion) {
		this.idCancion = idCancion;
	}

	public Cantante getCantante() {
		return this.cantante;
	}

	public void setCantante(Cantante cantante) {
		this.cantante = cantante;
	}

	public Disco getDisco() {
		return this.disco;
	}

	public void setDisco(Disco disco) {
		this.disco = disco;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDuracion() {
		return this.duracion;
	}

	public void setDuracion(String duracion) {
		this.duracion = duracion;
	}

	public String getEstilo() {
		return this.estilo;
	}

	public void setEstilo(String estilo) {
		this.estilo = estilo;
	}

}
