package com.modelo;
// Generated 8 feb 2023 10:45:20 by Hibernate Tools 5.6.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cantante generated by hbm2java
 */
public class Cantante implements java.io.Serializable {

	private Integer idCantante;
	private String nombre;
	private int edad;
	private String nacionalidad;
	private int numeroDiscosPlatinos;
	private Set cancions = new HashSet(0);

	public Cantante() {
	}

	public Cantante(String nombre, int edad, int numeroDiscosPlatinos) {
		this.nombre = nombre;
		this.edad = edad;
		this.numeroDiscosPlatinos = numeroDiscosPlatinos;
	}
	
	public Cantante(String nombre, int edad, String nacionalidad, int numeroDiscosPlatinos) {
		this.nombre = nombre;
		this.edad = edad;
		this.numeroDiscosPlatinos = numeroDiscosPlatinos;
		this.nacionalidad = nacionalidad;
	}

	public Cantante(String nombre, int edad, String nacionalidad, int numeroDiscosPlatinos, Set cancions) {
		this.nombre = nombre;
		this.edad = edad;
		this.nacionalidad = nacionalidad;
		this.numeroDiscosPlatinos = numeroDiscosPlatinos;
		this.cancions = cancions;
	}

	public Integer getIdCantante() {
		return this.idCantante;
	}

	public void setIdCantante(Integer idCantante) {
		this.idCantante = idCantante;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	public int getNumeroDiscosPlatinos() {
		return this.numeroDiscosPlatinos;
	}

	public void setNumeroDiscosPlatinos(int numeroDiscosPlatinos) {
		this.numeroDiscosPlatinos = numeroDiscosPlatinos;
	}

	public Set getCancions() {
		return this.cancions;
	}

	public void setCancions(Set cancions) {
		this.cancions = cancions;
	}

}
