package com.modelo;
// Generated 8 feb 2023 10:45:20 by Hibernate Tools 5.6.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Disco generated by hbm2java
 */
public class Disco implements java.io.Serializable {

	private Integer idDisco;
	private String nombre;
	private Date fechaSalida;
	private int numeroCanciones;
	private Set cancions = new HashSet(0);

	public Disco() {
	}

	public Disco(String nombre, Date fechaSalida, int numeroCanciones) {
		this.nombre = nombre;
		this.fechaSalida = fechaSalida;
		this.numeroCanciones = numeroCanciones;
	}

	public Disco(String nombre, Date fechaSalida, int numeroCanciones, Set cancions) {
		this.nombre = nombre;
		this.fechaSalida = fechaSalida;
		this.numeroCanciones = numeroCanciones;
		this.cancions = cancions;
	}

	public Integer getIdDisco() {
		return this.idDisco;
	}

	public void setIdDisco(Integer idDisco) {
		this.idDisco = idDisco;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaSalida() {
		return this.fechaSalida;
	}

	public void setFechaSalida(Date fechaSalida) {
		this.fechaSalida = fechaSalida;
	}

	public int getNumeroCanciones() {
		return this.numeroCanciones;
	}

	public void setNumeroCanciones(int numeroCanciones) {
		this.numeroCanciones = numeroCanciones;
	}

	public Set getCancions() {
		return this.cancions;
	}

	public void setCancions(Set cancions) {
		this.cancions = cancions;
	}

}
